// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// CategoriesColumns holds the columns for the "categories" table.
	CategoriesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "name", Type: field.TypeString, Unique: true, Size: 255},
		{Name: "description", Type: field.TypeString, Nullable: true},
		{Name: "color", Type: field.TypeString, Nullable: true, Size: 7},
		{Name: "suggested_percentage", Type: field.TypeInt, Nullable: true},
	}
	// CategoriesTable holds the schema information for the "categories" table.
	CategoriesTable = &schema.Table{
		Name:       "categories",
		Columns:    CategoriesColumns,
		PrimaryKey: []*schema.Column{CategoriesColumns[0]},
	}
	// InvoicesColumns holds the columns for the "invoices" table.
	InvoicesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "status", Type: field.TypeString, Default: "pending"},
		{Name: "amount", Type: field.TypeFloat64, Default: 0, SchemaType: map[string]string{"postgres": "decimal(10,2)"}},
		{Name: "title", Type: field.TypeString, Size: 255},
		{Name: "due_date", Type: field.TypeTime},
		{Name: "user_id", Type: field.TypeUUID},
	}
	// InvoicesTable holds the schema information for the "invoices" table.
	InvoicesTable = &schema.Table{
		Name:       "invoices",
		Columns:    InvoicesColumns,
		PrimaryKey: []*schema.Column{InvoicesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "invoices_users_user",
				Columns:    []*schema.Column{InvoicesColumns[7]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// TransactionsColumns holds the columns for the "transactions" table.
	TransactionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "record_type", Type: field.TypeString, Default: "expense"},
		{Name: "status", Type: field.TypeString, Default: "pending"},
		{Name: "amount", Type: field.TypeFloat64, SchemaType: map[string]string{"postgres": "decimal(10,2)"}},
		{Name: "title", Type: field.TypeString, Size: 255},
		{Name: "record_date", Type: field.TypeTime},
		{Name: "user_id", Type: field.TypeUUID},
		{Name: "invoice_id", Type: field.TypeUUID, Nullable: true},
		{Name: "category_id", Type: field.TypeUUID, Nullable: true},
	}
	// TransactionsTable holds the schema information for the "transactions" table.
	TransactionsTable = &schema.Table{
		Name:       "transactions",
		Columns:    TransactionsColumns,
		PrimaryKey: []*schema.Column{TransactionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "transactions_users_user",
				Columns:    []*schema.Column{TransactionsColumns[8]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "transactions_invoices_invoice",
				Columns:    []*schema.Column{TransactionsColumns[9]},
				RefColumns: []*schema.Column{InvoicesColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "transactions_categories_category",
				Columns:    []*schema.Column{TransactionsColumns[10]},
				RefColumns: []*schema.Column{CategoriesColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "transaction_record_date",
				Unique:  false,
				Columns: []*schema.Column{TransactionsColumns[7]},
			},
			{
				Name:    "transaction_record_type",
				Unique:  false,
				Columns: []*schema.Column{TransactionsColumns[3]},
			},
			{
				Name:    "transaction_invoice_id",
				Unique:  false,
				Columns: []*schema.Column{TransactionsColumns[9]},
			},
			{
				Name:    "transaction_category_id",
				Unique:  false,
				Columns: []*schema.Column{TransactionsColumns[10]},
			},
			{
				Name:    "transaction_record_date_record_type_category_id",
				Unique:  false,
				Columns: []*schema.Column{TransactionsColumns[7], TransactionsColumns[3], TransactionsColumns[10]},
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "name", Type: field.TypeString, Nullable: true, Size: 255},
		{Name: "username", Type: field.TypeString, Unique: true, Size: 255},
		{Name: "email", Type: field.TypeString, Unique: true, Nullable: true, Size: 255},
		{Name: "password_hash", Type: field.TypeString, Size: 255},
		{Name: "is_active", Type: field.TypeBool, Default: true},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		CategoriesTable,
		InvoicesTable,
		TransactionsTable,
		UsersTable,
	}
)

func init() {
	InvoicesTable.ForeignKeys[0].RefTable = UsersTable
	TransactionsTable.ForeignKeys[0].RefTable = UsersTable
	TransactionsTable.ForeignKeys[1].RefTable = InvoicesTable
	TransactionsTable.ForeignKeys[2].RefTable = CategoriesTable
}
