// Code generated by ent, DO NOT EDIT.

package ent

import (
	"frog-go/internal/ent/category"
	"frog-go/internal/ent/schemas"
	"frog-go/internal/ent/transaction"
	"time"

	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	categoryMixin := schemas.Category{}.Mixin()
	categoryMixinFields0 := categoryMixin[0].Fields()
	_ = categoryMixinFields0
	categoryMixinFields1 := categoryMixin[1].Fields()
	_ = categoryMixinFields1
	categoryFields := schemas.Category{}.Fields()
	_ = categoryFields
	// categoryDescCreatedAt is the schema descriptor for created_at field.
	categoryDescCreatedAt := categoryMixinFields1[0].Descriptor()
	// category.DefaultCreatedAt holds the default value on creation for the created_at field.
	category.DefaultCreatedAt = categoryDescCreatedAt.Default.(func() time.Time)
	// categoryDescUpdatedAt is the schema descriptor for updated_at field.
	categoryDescUpdatedAt := categoryMixinFields1[1].Descriptor()
	// category.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	category.DefaultUpdatedAt = categoryDescUpdatedAt.Default.(func() time.Time)
	// category.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	category.UpdateDefaultUpdatedAt = categoryDescUpdatedAt.UpdateDefault.(func() time.Time)
	// categoryDescName is the schema descriptor for name field.
	categoryDescName := categoryFields[0].Descriptor()
	// category.NameValidator is a validator for the "name" field. It is called by the builders before save.
	category.NameValidator = func() func(string) error {
		validators := categoryDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// categoryDescColor is the schema descriptor for color field.
	categoryDescColor := categoryFields[2].Descriptor()
	// category.ColorValidator is a validator for the "color" field. It is called by the builders before save.
	category.ColorValidator = categoryDescColor.Validators[0].(func(string) error)
	// categoryDescID is the schema descriptor for id field.
	categoryDescID := categoryMixinFields0[0].Descriptor()
	// category.DefaultID holds the default value on creation for the id field.
	category.DefaultID = categoryDescID.Default.(func() uuid.UUID)
	transactionMixin := schemas.Transaction{}.Mixin()
	transactionMixinFields0 := transactionMixin[0].Fields()
	_ = transactionMixinFields0
	transactionMixinFields1 := transactionMixin[1].Fields()
	_ = transactionMixinFields1
	transactionFields := schemas.Transaction{}.Fields()
	_ = transactionFields
	// transactionDescCreatedAt is the schema descriptor for created_at field.
	transactionDescCreatedAt := transactionMixinFields1[0].Descriptor()
	// transaction.DefaultCreatedAt holds the default value on creation for the created_at field.
	transaction.DefaultCreatedAt = transactionDescCreatedAt.Default.(func() time.Time)
	// transactionDescUpdatedAt is the schema descriptor for updated_at field.
	transactionDescUpdatedAt := transactionMixinFields1[1].Descriptor()
	// transaction.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	transaction.DefaultUpdatedAt = transactionDescUpdatedAt.Default.(func() time.Time)
	// transaction.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	transaction.UpdateDefaultUpdatedAt = transactionDescUpdatedAt.UpdateDefault.(func() time.Time)
	// transactionDescTitle is the schema descriptor for title field.
	transactionDescTitle := transactionFields[0].Descriptor()
	// transaction.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	transaction.TitleValidator = func() func(string) error {
		validators := transactionDescTitle.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(title string) error {
			for _, fn := range fns {
				if err := fn(title); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// transactionDescStatus is the schema descriptor for status field.
	transactionDescStatus := transactionFields[3].Descriptor()
	// transaction.DefaultStatus holds the default value on creation for the status field.
	transaction.DefaultStatus = transactionDescStatus.Default.(string)
	// transaction.StatusValidator is a validator for the "status" field. It is called by the builders before save.
	transaction.StatusValidator = func() func(string) error {
		validators := transactionDescStatus.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(status string) error {
			for _, fn := range fns {
				if err := fn(status); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// transactionDescKind is the schema descriptor for kind field.
	transactionDescKind := transactionFields[4].Descriptor()
	// transaction.DefaultKind holds the default value on creation for the kind field.
	transaction.DefaultKind = transactionDescKind.Default.(string)
	// transaction.KindValidator is a validator for the "kind" field. It is called by the builders before save.
	transaction.KindValidator = func() func(string) error {
		validators := transactionDescKind.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(kind string) error {
			for _, fn := range fns {
				if err := fn(kind); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// transactionDescID is the schema descriptor for id field.
	transactionDescID := transactionMixinFields0[0].Descriptor()
	// transaction.DefaultID holds the default value on creation for the id field.
	transaction.DefaultID = transactionDescID.Default.(func() uuid.UUID)
}
